kubernetes/kubectl

- pkg/kexpand/util.go
Move some util code from https://github.com/kubernetes/kubernetes/pull/52682 to kubectl repo.
There will a followup PR to move https://github.com/kubernetes/kubernetes/pull/52682/files#diff-0c3f4528c27638ae0b2b2fd6e2ecff6b code to kubectl repo. But it is blocked by some dependency issue of kubectl factory code.
> add kexpand util

- .travis.yml
- bin/consider-early-travis-exit.sh
Noticed that merging of
https://github.com/kubernetes/kubectl/blob/master/docs/maintainers/issue_backlog.md 
launched all the go gets, go tests, drama for no reason.
> Skip CICD build on markdown or doc changes.

- pkg/framework/test/apiserver_config.go
- pkg/framework/test/bin_path_finder.go
- pkg/framework/test/bin_path_finder_test.go
- pkg/framework/test/etcd.go
- pkg/framework/test/etcd_config.go
- pkg/framework/test/etcd_config_test.go
- pkg/framework/test/etcd_constructor_test.go
- pkg/framework/test/fixtures.go
- pkg/framework/test/port_finder.go
- pkg/framework/test/port_finder_test.go
[closes #161]
We need to do some calculation to find binary paths and free ports, so we can't make a 0-value Etcd struct useful. But we can provide a constructor that takes no arguments, and gives you good defaults.
Cc @hoegaarden @apelisse
> Add a sane default constructor for the Etcd and EtcdConfig structs

- pkg/framework/test/apiserver.go
- pkg/framework/test/apiserver_config.go
- pkg/framework/test/apiserver_config_test.go
- pkg/framework/test/apiserver_constructor_test.go
- pkg/framework/test/apiserver_test.go
- pkg/framework/test/bin_path_finder.go
- pkg/framework/test/bin_path_finder_test.go
- pkg/framework/test/democli/integration/integration_suite_test.go
- pkg/framework/test/democli/integration/integration_test.go
- pkg/framework/test/etcd.go
- pkg/framework/test/etcd_test.go
- pkg/framework/test/fixtures.go
- pkg/framework/test/fixtures_test.go
- pkg/framework/test/integration/integration_suite_test.go
- pkg/framework/test/integration/integration_test.go
- pkg/framework/test/testfakes/fake_fixture_process.go
[closes #163]
In the process of making the APIServer constructor take 0 arguments (#162), we naturally find ourselves making the Fixtures constructor take 0 arguments (#163).
We'll be cleaning things up even more as we continue to work on #162, but this seems like a reasonable mid-point where there's already some user-value. In particular, the main interface to the test framework (The Fixtures constructor and methods) ought to be stable now:
```go
myFixtures, err := test.NewFixtures()
err = myFixtures.Start()
myServerURL = myFixtures.APIServerURL()
// Run tests using myServerURL
err = myFixtures.Stop()
```
Cc @hoegaarden @apelisse
> Finalize the interface of the Fixtures struct

- pkg/apis/manifest/v1alpha1/types.go
- Update type definition for manifest to make align with https://github.com/kubernetes/kubernetes/blob/d8d680be6e2bd1455bb6861f9bd6ed7d4f7dce43/pkg/kubectl/configmap.go#L39-L44 and https://github.com/kubernetes/kubernetes/blob/d8d680be6e2bd1455bb6861f9bd6ed7d4f7dce43/pkg/kubectl/secret.go#L39-L44.
- Change `TLS` to be a pointer.
> update manifest types

- bin/pre-commit.sh
gofmt doesn't return an error exit code when it fails (because some
files are improperly formatted). Make sure that the output is empty
instead.
> pre-commit: Check gofmt output for errors

- pkg/kinflate/util/namereference.go
- pkg/kinflate/util/namereference_test.go
- pkg/kinflate/util/namereferenceconfig.go
- pkg/kinflate/util/pathconfig.go
This PR is based on top of https://github.com/kubernetes/kubectl/pull/218. The first 2 commits are from https://github.com/kubernetes/kubectl/pull/218.
Add util to update the name field that references another object's name.
> util to update name reference

- pkg/kinflate/commands/inflate.go
- pkg/kinflate/tree/builder.go
- pkg/kinflate/tree/builder_test.go
- pkg/kinflate/util/manifestloader.go
- pkg/kinflate/util/manifestloader_test.go
This is a partial refactor toward an organization which better supports kinlfate error messages. We recognize that both the Loader and ManifestLoader classes are incoherent, and we intend to address this issue in future PR's. We've included several TODO's.
> Checkpoint toward better kinflate error messages.

- pkg/kinflate/util/manifesterror.go
- pkg/kinflate/util/manifesterror_test.go
New structure (ManifestError) to encasulate info needed for descriptve errors while parsing, creating kinflate manifests.
> New structure: ManifestError

- pkg/kinflate/commands/addresource_test.go
- pkg/kinflate/commands/commands.go
- pkg/kinflate/commands/init.go
`kinflate init` generates a manifest file which contains
non-existent resources in `resources` section. This change
keeps those resources in commented form so that 'kinflate inflate'
doesnt barf at the user.
> kinflate: removed non-existing resources from manifest file

- cmd/kinflate/README.md
'go get' complains if package exists and has been checked out with
different protocol (https/git). This results in tutorial integration
test failures. Disabling the option untill we have a solid solution.
> removed '-u' option from install command

- pkg/kinflate/resource/secret.go
- pkg/kinflate/resource/secret_test.go
Create Resource from one `SecretGenerator` object.
It reads the command, executes the command and use the output as the secret data. 
When executing the command, it need a path `p`, which is the root directory containing Kube-manifest.YAML file. With #317, we can call this function by `NewFromSecretGenerator(s, loader.Root())`
> Add secret resource

- pkg/kinflate/resource/configmap_test.go
- pkg/loader/fileloader.go
- pkg/loader/loader.go
- pkg/loader/loader_test.go
- pkg/loader/loadertest/fake_loader.go
Allow the FakeLoader to be initialized with a directory; not just a full file path.
> Simplified Loader.New() to always take a directory

- pkg/kinflate/commands/addresource.go
- pkg/kinflate/commands/configmap.go
- pkg/kinflate/commands/set_name_prefix.go
- pkg/kinflate/commands/util.go
- pkg/kinflate/commands/util_test.go
This change removes all the dependency on package tree from sub commands add resource, add configmap, set nameprefix
> Add util functions to read/write manifest file and update sub commands

- pkg/kinflate/app/application.go
- pkg/kinflate/commands/testdata/testcase-single-overlay/expected.diff
- pkg/kinflate/commands/testdata/testcase-single-overlay/expected.yaml
- pkg/kinflate/commands/testdata/testcase-single-overlay/in/overlay/Kube-manifest.yaml
- pkg/kinflate/commands/testdata/testcase-single-overlay/in/overlay/deployment.yaml
- pkg/kinflate/commands/testdata/testcase-single-overlay/in/package/Kube-manifest.yaml
- pkg/kinflate/commands/testdata/testcase-single-overlay/in/package/deployment.yaml
@Liujingfang1 observed a bug the hash can be appended in multiple layers, e.g. `configmap-<hash1>-<hash2>`
The name hash transformer should be only applied to the configmap and secrets generated from the current layer.
> appending name hash only applies to current layer

- pkg/kinflate/app/application.go
- pkg/kinflate/commands/diff.go
- pkg/kinflate/commands/inflate.go
- pkg/kinflate/configmapandsecret/configmap_secret.go
- pkg/kinflate/transformers/labelsandannotations.go
- pkg/kinflate/transformers/labelsandannotations_test.go
- pkg/kinflate/transformers/multitransformer.go
- pkg/kinflate/transformers/namehash.go
- pkg/kinflate/transformers/namehash_test.go
- pkg/kinflate/transformers/namereference.go
- pkg/kinflate/transformers/namereference_test.go
- pkg/kinflate/transformers/nooptransformer.go
- pkg/kinflate/transformers/overlay.go
- pkg/kinflate/transformers/overlay_test.go
- pkg/kinflate/transformers/prefixname.go
- pkg/kinflate/transformers/transformer.go
- pkg/kinflate/transformers/util_test.go
- pkg/kinflate/types/types.go
- pkg/kinflate/util/util.go
- pkg/kinflate/util/util_test.go
There will be another PR to change the related function signature to return `ResourceCollection` instead of `[]*Resource`.
> Rename KObject to ResourceCollection

- pkg/kinflate/app/application.go
- pkg/kinflate/app/application_test.go
- pkg/kinflate/configmapandsecret/configmap_secret.go
- pkg/kinflate/resource/appresource.go
- pkg/kinflate/resource/appresource_test.go
- pkg/kinflate/resource/configmap.go
- pkg/kinflate/resource/configmap_test.go
- pkg/kinflate/resource/resource.go
- pkg/kinflate/resource/secret.go
- pkg/kinflate/resource/secret_test.go
- pkg/kinflate/resource/util.go
- pkg/kinflate/resource/util_test.go
- pkg/kinflate/transformers/labelsandannotations.go
- pkg/kinflate/transformers/labelsandannotations_test.go
- pkg/kinflate/transformers/multitransformer.go
- pkg/kinflate/transformers/namehash.go
- pkg/kinflate/transformers/namehash_test.go
- pkg/kinflate/transformers/namereference.go
- pkg/kinflate/transformers/namereference_test.go
- pkg/kinflate/transformers/nooptransformer.go
- pkg/kinflate/transformers/overlay.go
- pkg/kinflate/transformers/overlay_test.go
- pkg/kinflate/transformers/prefixname.go
- pkg/kinflate/transformers/prefixname_test.go
- pkg/kinflate/transformers/transformer.go
- pkg/kinflate/transformers/util_test.go
- pkg/kinflate/types/types.go
- pkg/kinflate/types/util.go
- pkg/kinflate/util/util.go
- pkg/kinflate/util/util_test.go
Change function signature to return ResourceCollection instead of []*Resource.
Cleanup tests and embed test data according the tott article `remove logic from the test`.
Moved ResourceCollection to resource pkg.
Most of this PR is mechanical change, nothing very interesting.
> cleanup Resouce slice related code

- cmd/kinflate/test/main.sh
Assume there is only one example directory we want to test. If we can find `tests/test.sh` inside that directory, we run the test against that dir.
Also remove lines `cd <dir>`
> Update directories in test script

- pkg/framework/predicates/map.go
- pkg/framework/predicates/map_test.go
- pkg/framework/predicates/number.go
- pkg/framework/predicates/number_test.go
- pkg/framework/predicates/slice.go
- pkg/framework/predicates/slice_test.go
- pkg/framework/predicates/string.go
- pkg/framework/predicates/string_test.go
- pkg/framework/predicates/value.go
- pkg/framework/predicates/value_test.go
- pkg/framework/unstructpath/example_test.go
- pkg/framework/unstructpath/mapf.go
- pkg/framework/unstructpath/maps.go
- pkg/framework/unstructpath/numbers.go
- pkg/framework/unstructpath/numbers_test.go
- pkg/framework/unstructpath/slicef.go
- pkg/framework/unstructpath/slices.go
- pkg/framework/unstructpath/strings.go
- pkg/framework/unstructpath/strings_test.go
- pkg/framework/unstructpath/valuef.go
- pkg/framework/unstructpath/values.go
Move the predicates to a "predicates" package, to simplify the
structure. This is purely mechanical change. Better documentation for
the package will come next, as well as a few other changes.
> unstructpath: Move predicates to their own package

- pkg/pluginutils/plugin_client.go
- pkg/pluginutils/plugin_client_test.go
- pkg/pluginutils/testdata/config
This will grab the context out of the config file if one is specified by the KUBECTL_GLOBAL_FLAG_CONTEXT passed in from the plugin framework.
@carolynvs might want to take a look at this.
> Use passed-in context in pluginutils config initializer

- pkg/kinflate/app/application.go
- pkg/kinflate/resource/appresource.go
- pkg/kinflate/resource/appresource_test.go
- pkg/kinflate/resource/util.go
- pkg/kinflate/transformers/overlay.go
- pkg/kinflate/transformers/overlay_test.go
Before: multiple patches against the same GVKN is not supported, because loaded patches are stored in the ResourceCollection which is indexed by GVKN. So it will complain if there are multiple patches for one GVKN.
After: loaded patches are stored in a slice of Resource.
> support multiple patches for the same GVKN

- cmd/kinflate/README.md
- cmd/kinflate/glossary.md
- cmd/kinflate/workflows.md
and pointers to it from the main README.
Need a place to define terminology.
This is a conversion and update of the content at go/kinflate-glossary
At the last minute, i pulled workflows out of the glossary, to make it a freestanding MD file, to which we can figures.  Perhaps this stuff goes into the main README, but trying to keep that short.
> Add glossary

- pkg/apis/manifest/v1alpha1/types.go
- pkg/kinflate/app/application.go
- pkg/kinflate/app/application_test.go
- pkg/kinflate/commands/testdata/testcase-simple/expected.diff
- pkg/kinflate/commands/testdata/testcase-simple/expected.yaml
- pkg/kinflate/commands/testdata/testcase-single-overlay/expected.diff
- pkg/kinflate/commands/testdata/testcase-single-overlay/expected.yaml
- pkg/kinflate/commands/testdata/testcase-single-overlay/in/overlay/Kube-manifest.yaml
- pkg/kinflate/constants/constants.go
- pkg/kinflate/resource/configmap.go
- pkg/kinflate/resource/resource.go
- pkg/kinflate/resource/util.go
In our current kindflate code, we don't support redefining configmap or secrets in overlays. If we want to change a configmap in the base, we are only allowed to apply a patch file containing the new configmap content.
This change is to enable us to redefine configmap in overlays. For example, in `base/Kube-manifest.yaml`, we define
```configMaps:
- name: demo-configmap
files:
- application.properties
```
In `instance/staging/Kube-manifest.yaml`, if we define it as
```configMaps:
- name: demo-configmap
behavior: replace
files:
- staging-application.properties
```
Then `staging-application.properties` is going to be used instead of `application.properties`.
In `instance/production/Kube-manifest.yaml`, if we define it as
```configMaps:
- name: demo-configmap
behavior: merge
files:
- …
```
> Add different behavior for configmaps in overlay

- pkg/apis/manifest/v1alpha1/types.go
- pkg/kinflate/commands/testdata/testcase-single-overlay/expected.diff
- pkg/kinflate/commands/testdata/testcase-single-overlay/expected.yaml
- pkg/kinflate/commands/testdata/testcase-single-overlay/in/overlay/Kube-manifest.yaml
- pkg/kinflate/commands/testdata/testcase-single-overlay/in/package/Kube-manifest.yaml
- pkg/kinflate/resource/secret.go
Add `Behavior` to `SecretGenerator`
Add test in `kinflate inflate` and `kinflate diff`
Since the logic is already handled in #373 , when we add `Behavior` for SecretGenerator, it automatically works.
> Add different behavior for secretGenerator in overlay

- cmd/kinflate/build/README.md
- cmd/kinflate/build/build.sh
- cmd/kinflate/build/cloudbuild.yaml
- cmd/kinflate/build/cloudbuild_local.yaml
Highlights:
- Adds a build script to generate the archive for Kinflate
- Adds configs for Google Container Builder to generate the build locally or in Google container builder
I have tested the build triggers with my fork.
> kinflate: add build automation

- cmd/kinflate/demo/helloWorldDetailed/customize.md
- cmd/kinflate/demo/helloWorldDetailed/manifest.md
- cmd/kinflate/demo/helloWorldDetailed/overlays/deploy.md
- cmd/kinflate/demo/helloWorldOnePager.md
- cmd/kinflate/demo/mySql.md
- pkg/kinflate/commands/inflate.go
- pkg/kinflate/commands/inflate_test.go
The manifest path is now just the first arg after the command.
If no arg specified, the current working directory is assumed.
> Remove the -f option of inflate

- pkg/kinflate/resource/util.go
Tested locally with ` kinflate inflate --alsologtostderr  --v 4 instances/staging`. 
Here is the output
``` 
I0405 16:07:23.576661  257572 decoder.go:224] decoding stream as YAML
I0405 16:07:23.577546  257572 decoder.go:224] decoding stream as YAML
I0405 16:07:23.578280  257572 util.go:116] Merge object map[kind:ConfigMap apiVersion:v1 metadata:map[name:my-demo-configmap creationTimestamp:<nil>] data:map[application.properties:app.name=Kinflate Demo for a Spring Boot application
]] with map[kind:ConfigMap apiVersion:v1 metadata:map[name:demo-configmap creationTimestamp:<nil>] data:map[application.properties:app.name=Staging Kinflate Demo
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://35.184.58.94:3306/db_example
spring.datasource.username=roott …
```
> Add logging for replacing and merging configmap and secrets

- cmd/kinflate/Makefile
- cmd/kinflate/docs/Kube-manifest.yaml
- cmd/kinflate/docs/glossary.md
We need some documentation for the manifest on the website.
Here's an initial structure, that uses the "kinflate init" command as a source of truth
to create an example that displays on the website.
To update the docs, create a branch, run "make docs", and merge the branch.
Down the road we could use the makefile to do more sophisticated inclusion of generated code with the website.
> structure for manifest documentation

- cmd/kustomize/demos/data/helloWorld/configMap.yaml
- cmd/kustomize/demos/data/helloWorld/deployment.yaml
- cmd/kustomize/demos/data/helloWorld/kustomization.yaml
- cmd/kustomize/demos/data/helloWorld/service.yaml
- cmd/kustomize/demos/helloWorld.md
- cmd/kustomize/docs/glossary.md
As part of the kinflate to kustomize rename, the org https://github.com/kinflate will be going away.
Also, it won't be replaced, since who would own the new org is problematic.  Perhaps we'll be able to put examples into their own repos under kubernetes-sigs, as siblings to the kustomize repo.  Until then, will pull the demo data in one at a time.  This PR pulls in helloworld.
> pull helloWorld demo data into code repo

- cmd/kustomize/demos/helloWorld.md
fix some wording now that this example no longer does "git clone"
> fix glitch in hello world

- cmd/kustomize/test/main.sh
This change is for the integration test of kustomize: kinflate-periodic-default-gke
It will pick up the ldap example from new location.
> change test script to use ldap from the new location

- OWNERS
Add an 'owners' section of the OWNERS file. Members of this section are specifically enumerated as the Subproject Owner role for the 'kubeclt' subproject in the SIG CLI charter.
> Add owners section for subproject owners

- SECURITY_CONTACTS
* Initial SECURITY_CONTACTS for the kubectl repo.
* Uses required template.
* These are the same contacts as every other kubernetes repo for now.
> Adds initial required SECURITY_CONTACTS file

- docs/book/pages/app_composition_and_deployment/accessing_multiple_clusters.md
- docs/book/pages/app_composition_and_deployment/diffing_local_and_remote_resources.md
- docs/book/pages/app_composition_and_deployment/structure_branches.md
- docs/book/pages/app_composition_and_deployment/structure_directories.md
- docs/book/pages/app_composition_and_deployment/structure_repositories.md
- docs/book/pages/app_management/apply.md
- docs/book/pages/app_management/container_images.md
- docs/book/pages/container_debugging/container_logs.md
- docs/book/pages/container_debugging/copying_container_files.md
- docs/book/pages/container_debugging/executing_a_command_in_a_container.md
- docs/book/pages/container_debugging/port_forward_to_pods.md
- docs/book/pages/container_debugging/proxying_traffic_to_services.md
- docs/book/pages/resource_printing/cluster_information.md
- docs/book/pages/resource_printing/describe.md
- docs/book/pages/resource_printing/fields.md
- docs/book/pages/resource_printing/queries_and_options.md
- docs/book/pages/resource_printing/raw.md
- docs/book/pages/resource_printing/summaries.md
- refactoring replaced '$ ' with 'deploy'
- should have replaced '$ ' with ''
> kubectl book: Fix exec examples caused by bad refactoring

- docs/book/pages/container_debugging/port_forward_to_pods.md
The examples at the end of the port_forward_to_pods page are derived
from the copying_container_files page when it was created.
> Remove cp examples from the port-forward page

- docs/book/pages/app_customization/bases_and_variants.md
- docs/book/pages/app_management/secrets_and_configmaps.md
Fix #642, The example ConfigMaps in the documentation have invalid DNS names which causes the `kubectl apply` or `kubectl apply -k .` command to fail with
```
The ConfigMap "myApplicationProperties-fm2tc275t4" is invalid: metadata.name: Invalid value: "myApplicationProperties-fm2tc275t4": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
```
Relevant Changes:
In _docs/book/pages/app_customization/bases_and_variants.md_ &  _docs/book/pages/app_management/secrets_and_configmaps.md_ 
**myJavaServerEnvVars** should be fixed to **my-java-server-env-vars**
In …
> Fix Invalid DNS ConfigMap Name

- docs/book/pages/app_management/secrets_and_configmaps.md
This adds an example of generating configmaps/secrets using the `env` option.
It also adds a bit of clarification that the same `literals`, `files` and `env` options can be used for secrets.
closes #632
> feat(docs): add section on environment style configmap/secret generation
