kubernetes/kubectl

- pkg/apis/manifest/v1alpha1/doc.go
- pkg/apis/manifest/v1alpha1/types.go
We finally agreed to land on kubectl repo.
Moved from main repo PR: https://github.com/kubernetes/kubernetes/pull/52570.
A lot of discussion there.
> add types for descriptor and manifest

- cmd/kexpand/README.md
- cmd/kexpand/main.go
A place to hang code.
Starting with `kexpand` since `expand` is already taken on linux systems, and since it's
unique enough to change with `find ./ | xargs sed -i 's/kexpand/foo/'`
> start kexpand

- docs/maintainers/MAINTAINERS.md
- new contributor tasks
- reporting at community meeting
- setting up f2f
> Add items to Maintainers tasks

- bin/pre-commit.sh
untabify and make the intent more obvious
> tweak precommit

- bin/pre-commit.sh
The current travis script currently fails if we have a `vendor/`
directory, and is also quite longer than necessary.
> Simplify travis script, work against `vendor/`

- pkg/kinflate/apps/apps_suite_test.go
- pkg/kinflate/apps/kind_visitor.go
- pkg/kinflate/apps/kind_visitor_test.go
- pkg/kinflate/configmapandsecret/configmap.go
- pkg/kinflate/configmapandsecret/env_file.go
- pkg/kinflate/configmapandsecret/secret.go
- pkg/kinflate/configmapandsecret/util/util.go
- pkg/kinflate/hash/hash.go
- pkg/kinflate/hash/hash_test.go
This PR copied the pkgs and added one field:
https://github.com/kubernetes/kubectl/pull/198/files#diff-02b8e163d2953b0f138313481b32d784R42
> copy some configmap and secret related pkgs for kinflate

- pkg/apis/manifest/v1alpha1/types.go
Per https://github.com/kubernetes/kubectl/pull/191#pullrequestreview-86986658
> format comments for types.go

- pkg/kinflate/pod_template_visitor/pod_template_visitor.go
Implement of pod template visitor for kinflate.
This PR depends on #198
> pod template visitor

- pkg/kinflate/configmap_secret.go
- pkg/kinflate/configmap_secret_test.go
- pkg/kinflate/util.go
This depends on #198 and #201.
> configmap and secret helper functions

- cmd/kinflate/kinflate.go
- cmd/kinflate/kinflate_test.go
- cmd/kinflate/testdata/simple/in/instances
- cmd/kinflate/testdata/simple/in/package
- cmd/kinflate/testdata/simple/out/expected.yaml
- pkg/kinflate/adjust_path.go
- pkg/kinflate/gvkn_sort.go
- pkg/kinflate/kinflate.go
- pkg/kinflate/util.go
There will be some test to replace https://github.com/kubernetes/kubectl/blob/c61d60e246663574dd531a0c61a99c325e81f809/cmd/kinflate/kinflate_test.go#L27-L32 soon.
> more support for configmap and secret

- pkg/kinflate/configmap_secret_test.go
- pkg/kinflate/update_test.go
[Travis](https://travis-ci.org/kubernetes/kubectl/builds/329076589#L521) showed those issues today.
cc: @totherme 
/assign @apelisse
> Fix formatting issues as suggested by gofmt

- cmd/kinflate/testdata/simple/out/expected.yaml
- pkg/kinflate/update.go
- pkg/kinflate/update_test.go
update mutate func:
- mutateField now takes a list of mutation func
- support create if not present
Fix a bug in the last commit.
> update mutate func

- pkg/kinflate/util/gvkn_sort.go
- pkg/kinflate/util/labelsandannotations.go
- pkg/kinflate/util/labelsandannotations_test.go
- pkg/kinflate/util/labelsandannotationsconfig.go
- pkg/kinflate/util/pathconfig.go
- pkg/kinflate/util/prefixname.go
- pkg/kinflate/util/prefixname_test.go
- pkg/kinflate/util/util.go
- pkg/kinflate/util/util_test.go
An implementation of `Transformer` interface to apply additional labels annotations.
> additional labels and annotations util

- cmd/kinflate/testdata/simple/out/expected.yaml
- pkg/kinflate/examples/simple/instances/exampleinstance/deployment/deployment.yaml
- pkg/kinflate/util/namereference.go
Fix an issue when failing to find the name of a configmap or a secret.
> fix name ref issue

- cmd/kinflate/kinflate.go
- pkg/kinflate/commands/configmap.go
This is empty and does nothing.
> kinflate: Create AddConfigMap structure

- Gopkg.lock
- cmd/kinflate/README.md
> modifyREADME

- pkg/kinflate/commands/addresource.go
- pkg/kinflate/commands/configmap.go
- pkg/kinflate/commands/configmap_test.go
- pkg/kinflate/commands/data_config.go
- pkg/kinflate/util.go
- pkg/kinflate/util/adjust_path.go
- pkg/kinflate/util/manifestloader.go
- pkg/kinflate/util/manifestloader_test.go
This PR adds "configmap" command to kinflate.
> Add configmap

- pkg/kinflate/commands/init.go
> fix a typo init.go

- pkg/kinflate/transformers/overlay.go
Address some comments from https://github.com/kubernetes/kubectl/pull/274:
- error out when a patch has not matching object
- it stop deleting the object from the overlay KObject.
> error out when a patch has not matching object

- cmd/kinflate/README.md
- cmd/kinflate/longerDemo/README.md
- cmd/kinflate/longerDemo/base.md
- cmd/kinflate/longerDemo/customization.md
- cmd/kinflate/longerDemo/identity.md
- cmd/kinflate/longerDemo/instances/README.md
- cmd/kinflate/longerDemo/instances/compare.md
- cmd/kinflate/longerDemo/instances/production.md
- cmd/kinflate/longerDemo/instances/staging.md
- cmd/kinflate/longerDemo/lifecycle.md
- cmd/kinflate/longerDemo/manifest.md
- cmd/kinflate/longerDemo/resources.md
- cmd/kinflate/shortDemo.md
Add links to existing demo and tutorial pages.
> Add links to existing demo and tutorial pages.

- bin/pre-commit.sh
It's too difficult to read travis output and understand how many failures happened and where they occurred, because the output is one continuous stream and by design accumulates errors, only reporting a logical OR at the end.
This change increases the readability of the output, and makes it easy to add new tests that report themselves in a consistent fashion.
> Make test failures easier to see and understand.

- pkg/kinflate/commands/inflate.go
- pkg/kinflate/tree/builder.go
- pkg/kinflate/tree/builder_test.go
- pkg/kinflate/util/manifestloader.go
- pkg/kinflate/util/manifestloader_test.go
Replaced the os.Stat by filesystem.Stat in builder.go
Improved the error message when loading resources
> WIP: fix filesystem tech debt

- cmd/kinflate/README.md
- cmd/kinflate/getting_started.md
Improves README.md
Added Getting Started guide
> kinflate: improved README and added getting-started

- pkg/kinflate/commands/set_name_prefix.go
Use ManifestLoader to clean the TODO item in set_name_prefix.go
> Use ManifestLoader to read and write the kubemanifest file

- pkg/kinflate/app/application.go
- pkg/kinflate/resource/resource.go
Includes the first pass at the Resource interface
> First pass at Application abstraction with unimplemented methods

- pkg/kinflate/commands/inflate_test.go
make all the yaml pkgs we use consist.
> update yaml import pkg

- pkg/kinflate/resource/configmap.go
- pkg/kinflate/resource/resource.go
This is a very early idea of implementing resource for configmap objects just to get a handle on the shape of the solution.
> added configmap resource implementation

- pkg/kinflate/resource/appresource.go
- pkg/kinflate/resource/appresource_test.go
- pkg/kinflate/resource/configmap.go
- pkg/kinflate/resource/configmap_test.go
- pkg/kinflate/resource/secret.go
- pkg/kinflate/resource/secret_test.go
This PR will be useful for implementing Resources func for applicationImpl in https://github.com/kubernetes/kubectl/pull/322.
> update resource package

- pkg/kinflate/commands/inflate.go
The change is covered by existing tests.
Note:
We will have a different PR to remove the mode flag and add tests for `kinflate diff`.
The type `KObject` will be removed in the future.
> Change inflate to use Application interface

- pkg/framework/unstructpath/doc.go
- pkg/framework/unstructpath/example_test.go
- pkg/framework/unstructpath/mapf.go
- pkg/framework/unstructpath/mapp.go
- pkg/framework/unstructpath/mapp_test.go
- pkg/framework/unstructpath/maps.go
- pkg/framework/unstructpath/numberp.go
- pkg/framework/unstructpath/numberp_test.go
- pkg/framework/unstructpath/numbers.go
- pkg/framework/unstructpath/numbers_test.go
- pkg/framework/unstructpath/slicef.go
- pkg/framework/unstructpath/slicep.go
- pkg/framework/unstructpath/slicep_test.go
- pkg/framework/unstructpath/slices.go
- pkg/framework/unstructpath/stringp.go
- pkg/framework/unstructpath/stringp_test.go
- pkg/framework/unstructpath/strings.go
- pkg/framework/unstructpath/strings_test.go
- pkg/framework/unstructpath/valuef.go
- pkg/framework/unstructpath/valuep.go
- pkg/framework/unstructpath/valuep_test.go
- pkg/framework/unstructpath/values.go
- pkg/framework/unstructpath/values_test.go
This package let's you find specific path in your unstruct types, kind
of like jsonpath does. But this is statically compile.
This replaces #258 
It doesn't have the controversial types anymore.
> unstructpath: Create json path type package.

- cmd/kinflate/README.md
- cmd/kinflate/getting_started.md
- cmd/kinflate/longerDemo/README.md
- cmd/kinflate/longerDemo/clone.md
- cmd/kinflate/longerDemo/manifest.md
- cmd/kinflate/longerDemo/overlays/README.md
- cmd/kinflate/longerDemo/overlays/compare.md
- cmd/kinflate/longerDemo/overlays/deploy.md
- cmd/kinflate/longerDemo/overlays/production/manifest.md
- cmd/kinflate/longerDemo/overlays/production/patch.md
- cmd/kinflate/longerDemo/overlays/staging/manifest.md
- cmd/kinflate/longerDemo/overlays/staging/patch.md
- cmd/kinflate/shortDemo.md
Tighten the home page and the mysql example.
> newshortdemo

- .travis.yml
- cmd/kinflate/README.md
- cmd/kinflate/demoHelloWorldLong/overlays/production/manifest.md
- cmd/kinflate/demoHelloWorldLong/overlays/staging/manifest.md
- cmd/kinflate/demoMySql.md
- pkg/kinflate/app/application.go
- pkg/kinflate/app/application_test.go
- pkg/kinflate/commands/testdata/testcase-base-only/in/Kube-manifest.yaml
- pkg/kinflate/commands/testdata/testcase-single-overlay/in/overlay/Kube-manifest.yaml
- pkg/kinflate/commands/testdata/testcase-single-overlay/in/package/Kube-manifest.yaml
- pkg/kinflate/examples/simple/instances/exampleinstance/Kube-manifest.yaml
- pkg/kinflate/examples/simple/package/Kube-manifest.yaml
This PR depends https://github.com/kinflate/tuthello/pull/2.
> detect unknown fields in Kube-manifest.yaml

- cmd/kinflate/version/version.go
- pkg/kinflate/commands/commands.go
add version package. Will be using it in container builder to embed version in all the releases. It will help us during debugging any external issues.
> kinflate: added version command

- pkg/pluginutils/plugin_client.go
- pkg/pluginutils/plugin_client_test.go
-add namespace overriding based on kubectl plugin env var
We added namespace overriding in svcat's standalone mode, so we need to be able to override it in plugin mode as well. I figured while I was in here, I might as well make the init method return the whole config, in case we need to pull anything off it in the future.
Thanks!
> Return rest config and regular config  from pluginutil Init method

- Gopkg.lock
- vendor/k8s.io/apimachinery/pkg/apis/meta/v1/duration.go
- vendor/k8s.io/apimachinery/pkg/apis/meta/v1/micro_time.go
- vendor/k8s.io/apimachinery/pkg/apis/meta/v1/time.go
- vendor/k8s.io/apimachinery/pkg/apis/meta/v1/unstructured/unstructured.go
- vendor/k8s.io/apimachinery/pkg/apis/meta/v1/unstructured/unstructured_list.go
- vendor/k8s.io/apimachinery/pkg/apis/meta/v1/unstructured/unstructured_test.go
- vendor/k8s.io/apimachinery/pkg/apis/meta/v1/validation/validation.go
- vendor/k8s.io/apimachinery/pkg/runtime/converter.go
- vendor/k8s.io/apimachinery/pkg/runtime/interfaces.go
- vendor/k8s.io/apimachinery/pkg/runtime/schema/group_version_test.go
- vendor/k8s.io/apimachinery/pkg/runtime/testing/types.go
- vendor/k8s.io/apimachinery/pkg/types/namespacedname.go
- vendor/k8s.io/apimachinery/pkg/util/httpstream/spdy/roundtripper_test.go
- vendor/k8s.io/apimachinery/pkg/util/strategicpatch/patch.go
- vendor/k8s.io/apimachinery/pkg/watch/filter.go
- vendor/k8s.io/apimachinery/pkg/watch/mux.go
Pick up the change in https://github.com/kubernetes/kubernetes/pull/61905 for https://github.com/kubernetes/kubectl/pull/375
> update vendor apimachinery

- cmd/kinflate/demos/helloWorld.md
- cmd/kinflate/demos/mySql.md
- cmd/kinflate/version/version.go
- pkg/kinflate/commands/build.go
- pkg/kinflate/commands/build_test.go
- pkg/kinflate/commands/commands.go
- pkg/kinflate/commands/configmap.go
- pkg/kinflate/commands/diff_test.go
- pkg/kinflate/commands/init.go
* inflate becomes build
* edit sits on top of add, set, etc.
> Command organization - build and edit

- cmd/kinflate/demos/README.md
- cmd/kinflate/demos/springboot.md
first revision of spring boot example demo
> Add springboot example demo

- pkg/kinflate/commands/build_test.go
- pkg/kinflate/commands/diff_test.go
- pkg/kinflate/commands/testdata/testcase-multiple-patches-conflict/in/overlay/Kube-manifest.yaml
- pkg/kinflate/commands/testdata/testcase-multiple-patches-conflict/in/overlay/deployment-patch1.yaml
- pkg/kinflate/commands/testdata/testcase-multiple-patches-conflict/in/overlay/deployment-patch2.yaml
- pkg/kinflate/commands/testdata/testcase-multiple-patches-conflict/in/package/Kube-manifest.yaml
- pkg/kinflate/commands/testdata/testcase-multiple-patches-conflict/in/package/deployment.yaml
- pkg/kinflate/commands/testdata/testcase-multiple-patches-conflict/in/package/service.yaml
- pkg/kinflate/commands/testdata/testcase-multiple-patches-conflict/test.yaml
- pkg/kinflate/commands/testdata/testcase-multiple-patches-noconflict/expected.diff
- pkg/kinflate/commands/testdata/testcase-multiple-patches-noconflict/expected.yaml
- pkg/kinflate/commands/testdata/testcase-multiple-patches-noconflict/in/overlay/Kube-manifest.yaml
- pkg/kinflate/commands/testdata/testcase-multiple-patches-noconflict/in/overlay/deployment-patch1.yaml
- pkg/kinflate/commands/testdata/testcase-multiple-patches-noconflict/in/overlay/deployment-patch2.yaml
- pkg/kinflate/commands/testdata/testcase-multiple-patches-noconflict/in/package/Kube-manifest.yaml
- pkg/kinflate/commands/testdata/testcase-multiple-patches-noconflict/in/package/deployment.yaml
- pkg/kinflate/commands/testdata/testcase-multiple-patches-noconflict/in/package/service.yaml
- pkg/kinflate/commands/testdata/testcase-multiple-patches-noconflict/test.yaml
- pkg/kinflate/transformers/overlay.go
- pkg/kinflate/transformers/overlay_test.go
- pkg/kinflate/transformers/overlayconflictdetector.go
Support conflict detection for patches in the same Kube-manifest.yaml.
This depends on https://github.com/kubernetes/kubernetes/pull/61905.
> Conflict detection in kinflate

- cmd/kinflate/demos/helloWorld.md
This demonstrates how configmap changes result in name changes
that force rolling updates for deployments.
Since the demo is tested, this 
Fixes #422
> Test config map names

- pkg/kustomize/transformers/namereferenceconfig.go
highlights:
RBAC references
ServiceAccountName reference
StatefulSet headless service reference
> updated namereference config for missing references.

- cmd/kustomize/demos/mySql.md
- cmd/kustomize/demos/springboot.md
This partially addresses both #429 (remove init from everything) and #432 (remove manifest from everything).
> Remove init and manifest from demos

- cmd/kustomize/demos/helloWorld.md
- cmd/kustomize/demos/mySql.md
- cmd/kustomize/demos/springboot.md
- cmd/kustomize/docs/kustomize.yaml
- pkg/kustomize/app/application.go
- pkg/kustomize/app/application_test.go
- pkg/kustomize/commands/init.go
- pkg/kustomize/commands/testdata/testcase-base-only/in/kustomize.yaml
- pkg/kustomize/commands/testdata/testcase-multiple-patches-conflict/in/overlay/kustomize.yaml
- pkg/kustomize/commands/testdata/testcase-multiple-patches-conflict/in/package/kustomize.yaml
- pkg/kustomize/commands/testdata/testcase-multiple-patches-noconflict/in/overlay/kustomize.yaml
- pkg/kustomize/commands/testdata/testcase-multiple-patches-noconflict/in/package/kustomize.yaml
- pkg/kustomize/commands/testdata/testcase-single-overlay/in/overlay/kustomize.yaml
- pkg/kustomize/commands/testdata/testcase-single-overlay/in/package/kustomize.yaml
- pkg/kustomize/examples/simple/instances/exampleinstance/kustomize.yaml
- pkg/kustomize/examples/simple/package/kustomize.yaml
- pkg/kustomize/types/kustomization.go
* drop `kustomizationName` and `description`
* change `objectLabels` to `labelsToAdd`
* change `objectAnnotations` to `annotationsToAdd`
> Some kustomization field renaming.

- cmd/kustomize/docs/kustomize.yaml
> Example kustomize.yaml

- cmd/kustomize/README.md
- cmd/kustomize/demos/README.md
- cmd/kustomize/demos/breakfast.md
- cmd/kustomize/docs/glossary.md
it's not just about k8s resources.
> add a tested breakfast configuration demo

- cmd/kustomize/docs/glossary.md
> Typo fix: resourse->resource

- cmd/kustomize/demos/README.md
- cmd/kustomize/docs/glossary.md
mySql->MySQL
refers to to->refers to
> Typo fix in glossary.md

- cmd/kustomize/demos/springboot.md
- pkg/kustomize/commands/addpatch.go
- pkg/kustomize/commands/addpatch_test.go
- pkg/kustomize/commands/commands.go
- pkg/kustomize/commands/util.go
Adds a new sub-command for adding patches to the kustomization file.
```
kustomize edit add patch my_neat_patch.yaml
```
Also updated the springboot demo to use the new command instead of sed.
> Add subcommand for adding patches to the kustomization file

- pkg/kustomize/commands/util_test.go
> Typo fix in the returned info.

- cmd/kustomize/demos/configGeneration.md
Line 148: defintion->definition
> Typo fix: defintion->definition

- cmd/kustomize/demos/data/ldap/base/deployment.yaml
- cmd/kustomize/demos/data/ldap/base/env.startup.txt
- cmd/kustomize/demos/data/ldap/base/kustomization.yaml
- cmd/kustomize/demos/data/ldap/base/service.yaml
- cmd/kustomize/demos/data/ldap/base/tests/test.sh
- cmd/kustomize/demos/data/ldap/overlays/production/deployment.yaml
- cmd/kustomize/demos/data/ldap/overlays/production/kustomization.yaml
- cmd/kustomize/demos/data/ldap/overlays/staging/config.env
- cmd/kustomize/demos/data/ldap/overlays/staging/deployment.yaml
- cmd/kustomize/demos/data/ldap/overlays/staging/kustomization.yaml
`base` folder is copied from `kinflate/example-ldap`
`overlays` folder is copied from `kinflate/example-ldap-instances`
> Add ldap example to demo data

- cmd/kustomize/demos/README.md
- cmd/kustomize/demos/ldap.md
locally tested by `bin/pre-commit.sh`
> Add ldap demo

- cmd/kustomize/docs/glossary.md
> Typo fix: cluser->cluster

- pkg/framework/path/selectors/interface.go
> fix some typos

- docs/book/npm-shrinkwrap.json
- docs/book/package.json
add gitbook-cli into kubectl book package.json
Necessary for hosting on netlify
> add gitbook-cli into kubectl book package.json

- docs/book/SUMMARY.md
- docs/book/pages/app_composition_and_deployment/publishing_bases.md
- docs/book/pages/app_composition_and_deployment/structure_branches.md
- docs/book/pages/app_composition_and_deployment/structure_directories.md
- docs/book/pages/app_composition_and_deployment/structure_multi_tier_apps.md
- docs/book/pages/app_composition_and_deployment/structure_repositories.md
- Also make them more clearly Alpha
> GitBook: Refine App Composition and Deployment guidelines

- docs/book/SUMMARY.md
- docs/book/pages/app_composition_and_deployment/structure_directories.md
- docs/book/pages/app_composition_and_deployment/structure_multi_tier_apps.md
- Also make them more clearly Alpha / Beta
> Refine App Composition and Deployment guidelines

- docs/book/pages/app_composition_and_deployment/accessing_multiple_clusters.md
- docs/book/pages/app_composition_and_deployment/diffing_local_and_remote_resources.md
- docs/book/pages/app_composition_and_deployment/structure_branches.md
- docs/book/pages/app_composition_and_deployment/structure_directories.md
- docs/book/pages/app_composition_and_deployment/structure_repositories.md
- docs/book/pages/app_customization/customizing_pod_templates.md
- docs/book/pages/app_management/apply.md
- docs/book/pages/app_management/container_images.md
- docs/book/pages/container_debugging/container_logs.md
- docs/book/pages/container_debugging/copying_container_files.md
- docs/book/pages/container_debugging/executing_a_command_in_a_container.md
- docs/book/pages/container_debugging/port_forward_to_pods.md
- docs/book/pages/container_debugging/proxying_traffic_to_services.md
- docs/book/pages/resource_printing/cluster_information.md
- docs/book/pages/resource_printing/describe.md
- docs/book/pages/resource_printing/fields.md
- docs/book/pages/resource_printing/queries_and_options.md
- docs/book/pages/resource_printing/raw.md
- docs/book/pages/resource_printing/summaries.md
- update the customizing pod template with `newName`
> kubectl book - add `newName` function

- docs/book/pages/app_management/field_merge_semantics.md
- docs/book/pages/resource_printing/cluster_information.md
> fix(docs): Fix typo and command reference

- docs/book/pages/container_debugging/copying_container_files.md
- docs/book/pages/container_debugging/port_forward_to_pods.md
> replaced Conainer with Container

- docs/book/package.json
> Update lodash to address CVE-2018-16487

- docs/book/Dockerfile
A Dockerfile for making it easier to run the GitBook locally when making changes
> Dockerfile for GitBook

- docs/book/pages/reference/kustomize.md
https://kubectl.docs.kubernetes.io/pages/reference/kustomize.html#patchesjson6902
> Fix patchesJson6902 example patch file.

- pkg/describe/describe.go
Implement grpc probe action
Kubernetes-commit: e4952f32b79b69bfa9333ff9da26a2da13859148
Signed-off-by: Davanum Srinivas <davanum@gmail.com>
Sorry, we do not accept changes directly against this repository. Please see
CONTRIBUTING.md for information on where and how to contribute instead.
> Add missing commit - Merge pull request #106463 from SergeyKanzhelev/grpcProbe
